apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: metrics-server

resources:
  - git::https://github.com/kubernetes-sigs/metrics-server.git//deploy/kubernetes?ref=v0.7.2
