on:
  push:
    branches:
      - main
  
permissions:
  contents: write
  pull-requests: write
  id-token: write
  
name: release-please
  
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:

    - uses: octo-sts/action@v1.0.0
      id: octo-sts
      with:
        scope: sharing-fish
        identity: deploy-main

    - uses: googleapis/release-please-action@v4
      with:
        token: ${{ steps.octo-sts.outputs.token }}
        release-type: simple