on:
  push:
    branches:
      - main
  
permissions:
  contents: write
  pull-requests: write
  id-token: write
  
name: release-please
  
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:

    - uses: octo-sts/action@v1.0.0
      id: octo-sts
      with:
        scope: sharing-fish
        identity: library-main

    - name: Install Terraform and Terragrunt
      uses: alexellis/arkade-get@493cf9387f80dcbf8a85786c55e04de45c927a5c
      with:
        terraform: latest

    - name: Format Terraform files
      run: terraform fmt -recursive -check

    - uses: googleapis/release-please-action@v4
      with:
        token: ${{ steps.octo-sts.outputs.token }}
        config-file: release-please-config.json
        manifest-file: .release-please-manifest.json